"""add week_visit_plan to users

Revision ID: 2c5b91144fb3
Revises: b4ebed4b9f44
Create Date: 2025-12-01 21:22:10.307596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5b91144fb3'
down_revision: Union[str, None] = 'b4ebed4b9f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('week_visit_plan', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'week_visit_plan')
    # ### end Alembic commands ###
