"""is_workday - add to calendar_dates

Revision ID: 4292d5261b3a
Revises: 10ae83b11e3e
Create Date: 2025-10-02 17:55:13.950684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4292d5261b3a'
down_revision: Union[str, None] = '10ae83b11e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_dates', sa.Column('is_workday', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_dates', 'is_workday')
    # ### end Alembic commands ###
