"""Refactoring_4

Revision ID: 44953ba15352
Revises: e44dd5c32b66
Create Date: 2025-07-22 21:45:52.932813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44953ba15352'
down_revision: Union[str, Sequence[str], None] = 'e44dd5c32b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_capacity_weekdays', sa.Column('short_name', sa.Text(), nullable=True))
    op.add_column('office_capacity_weekdays', sa.Column('name', sa.Text(), nullable=True))

    # 1. OfficeCapacityWeekday
    office_capacity_weekdays = sa.table(
        "office_capacity_weekdays",
        sa.column("weekday", sa.SmallInteger),
        sa.column("short_name", sa.Text()),
        sa.column("name", sa.Text()),
        sa.column("capacity", sa.Integer)
    )

    op.bulk_insert(
        office_capacity_weekdays,
        [
            {"weekday": 1, "short_name": "ПН", "name": "Понедельник", "capacity": 12},
            {"weekday": 2, "short_name": "ВТ", "name": "Вторник", "capacity": 12},
            {"weekday": 3, "short_name": "СР", "name": "Среда", "capacity": 12},
            {"weekday": 4, "short_name": "ЧТ", "name": "Четверг", "capacity": 12},
            {"weekday": 5, "short_name": "ПТ", "name": "Пятница", "capacity": 12},
            {"weekday": 6, "short_name": "СБ", "name": "Суббота", "capacity": 12},
            {"weekday": 7, "short_name": "ВС", "name": "Воскресенье", "capacity": 12}
        ],
    )

    # 2. BookingStateDict
    booking_state_dict = sa.table(
        "booking_state_dict",
        sa.column("code", sa.Text),
        sa.column("kind", sa.Text),
        sa.column("description", sa.Text),
    )

    op.bulk_insert(
        booking_state_dict,
        [
            # --- статусы ---
            {"code": "reserved", "kind": "status", "description": "Забронирован"},
            {"code": "confirmed", "kind": "status", "description": "Подтверждён"},
            {"code": "cancelled", "kind": "status", "description": "Отменён"},
            # --- источники ---
            {"code": "user", "kind": "source", "description": "Вручную"},
            {"code": "auto_pattern", "kind": "source", "description": "Ботом"},
            {"code": "waitlist_promote", "kind": "source", "description": "Из листа ожидания"},
            {"code": "admin", "kind": "source", "description": "Администратором"},
        ],
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office_capacity_weekdays', 'name')
    op.drop_column('office_capacity_weekdays', 'short_name')
    # ### end Alembic commands ###
