"""Refactoring_7

Revision ID: 5dc9ad12a29a
Revises: d090a9113a2c
Create Date: 2025-07-24 00:46:04.529957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc9ad12a29a'
down_revision: Union[str, Sequence[str], None] = 'd090a9113a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('waitlist_user_id_cal_date_key', 'waitlist', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('waitlist_user_id_cal_date_key', 'waitlist', ['user_id', 'cal_date'])
    # ### end Alembic commands ###
