"""Refactoring

Revision ID: 623b8b8b20d3
Revises: 
Create Date: 2025-07-21 18:46:02.815485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623b8b8b20d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_state_dict',
    sa.Column('state_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('calendar_dates',
    sa.Column('cal_date', sa.Date(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cal_date')
    )
    op.create_table('friday_prompts_log',
    sa.Column('prompt_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sent_on', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('recipients_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_table('office_capacity_weekdays',
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('weekday')
    )
    op.create_table('system_config',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('cal_date', sa.Date(), nullable=False),
    sa.Column('status_id', sa.SmallInteger(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('auto_confirm_applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cal_date'], ['calendar_dates.cal_date'], ),
    sa.ForeignKeyConstraint(['source_id'], ['booking_state_dict.state_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['booking_state_dict.state_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id'),
    sa.UniqueConstraint('user_id', 'cal_date')
    )
    op.create_table('user_prompt_status',
    sa.Column('prompt_status_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_pattern_applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('skipped', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['friday_prompts_log.prompt_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('prompt_status_id'),
    sa.UniqueConstraint('prompt_id', 'user_id')
    )
    op.create_table('user_recurring_weekdays',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'weekday'),
    sa.UniqueConstraint('user_id', 'weekday')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('auto_confirm', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('default_remind_friday', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_vacations',
    sa.Column('vacation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vacation_id')
    )
    op.create_table('waitlist',
    sa.Column('waitlist_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('cal_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('promoted_booking_id', sa.BigInteger(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cal_date'], ['calendar_dates.cal_date'], ),
    sa.ForeignKeyConstraint(['promoted_booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('waitlist_id'),
    sa.UniqueConstraint('user_id', 'cal_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waitlist')
    op.drop_table('user_vacations')
    op.drop_table('user_settings')
    op.drop_table('user_recurring_weekdays')
    op.drop_table('user_prompt_status')
    op.drop_table('bookings')
    op.drop_table('users')
    op.drop_table('system_config')
    op.drop_table('office_capacity_weekdays')
    op.drop_table('friday_prompts_log')
    op.drop_table('calendar_dates')
    op.drop_table('booking_state_dict')
    # ### end Alembic commands ###
