"""Refactoring_2

Revision ID: 6482bdeac837
Revises: 623b8b8b20d3
Create Date: 2025-07-21 22:31:38.820627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6482bdeac837'
down_revision: Union[str, Sequence[str], None] = '623b8b8b20d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_recurring_weekdays', ['user_id', 'weekday'])
    op.add_column('user_settings', sa.Column('default_remind', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user_settings', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('user_settings', 'default_remind_friday')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('default_remind_friday', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('user_settings', 'is_admin')
    op.drop_column('user_settings', 'default_remind')
    op.drop_constraint(None, 'user_recurring_weekdays', type_='unique')
    # ### end Alembic commands ###
