"""upgrade users, add professions, products

Revision ID: 8dbff4f076dd
Revises: bb0c04c61425
Create Date: 2025-09-08 19:14:33.224912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbff4f076dd'
down_revision: Union[str, None] = 'bb0c04c61425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professions',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('is_lead', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('profession_id', sa.SmallInteger(), nullable=False))
    op.add_column('users', sa.Column('product_id', sa.SmallInteger(), nullable=False))
    op.create_foreign_key(None, 'users', 'professions', ['profession_id'], ['id'])
    op.create_foreign_key(None, 'users', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'product_id')
    op.drop_column('users', 'profession_id')
    op.drop_column('users', 'is_lead')
    op.drop_table('professions')
    op.drop_table('products')
    # ### end Alembic commands ###
