"""add booking index

Revision ID: b4ebed4b9f44
Revises: 4c325510dcc2
Create Date: 2025-10-21 00:11:10.785237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ebed4b9f44'
down_revision: Union[str, None] = '4c325510dcc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_booking_cal_date_status_created', 'bookings', ['cal_date', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_booking_cal_date_status_created', table_name='bookings')
    # ### end Alembic commands ###
