"""Refactoring_6

Revision ID: d090a9113a2c
Revises: 0a3b56d4a246
Create Date: 2025-07-23 19:44:54.546732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd090a9113a2c'
down_revision: Union[str, Sequence[str], None] = '0a3b56d4a246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_user_id_cal_date_key', 'bookings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bookings_user_id_cal_date_key', 'bookings', ['user_id', 'cal_date'])
    # ### end Alembic commands ###
